name: Publish Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install project dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        run: poetry publish --build --username __token__ --password pypi-AgEIcHlwaS5vcmcCJDBhN2RjMWM1LWZmN2ItNDk5My1hNzIxLWY1ZTNmYmRhNmY2NgACKlszLCIxZjMxNzAxMS03M2Y1LTQyM2MtOTIyNC03ZTBlNzNkNDE2ZmIiXQAABiA4o0tlslo-D9QP-v2SgkNHVdEgcJj1HrNp8oLmKIUwFg
